spring:
  application:
    name: JPADemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: mysqlroot2010!!
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
test:
  classpath: com.example.EmployeeManagementSystem.service.ServiceEmployee
  classpath-sub: com.example.EmployeeManagementSystem.service.ServiceEmployee$SubEmployee
  path2: com/example/EmployeeManagementSystem/service/ServiceEmployee.java
